version: 2
jobs:
  install:
    docker:
      - image: circleci/node:10.15.3
    #   - image: postgres:11.2
    #     command: -p 7071
    #     environment:
    #       POSTGRES_USER: postgres
    #       POSTGRES_DB: pfms
    working_directory: ~/repo
    steps:
      - checkout
      - run: sudo apt-get update

      # install postgres client
      # - run: sudo apt install -y postgresql-client || true

      # load seed script for data base
      # - run: psql -U postgres -h localhost -p 7071 -d pfms -f docker/postgres/schema.sql

      - restore_cache:
          key: v2-deps-app-{{ checksum "package-lock.json" }}
      - restore_cache:
          key: v2-deps-client-{{ checksum "client/package-lock.json" }}
      - restore_cache:
          key: v2-deps-server-{{ checksum "server/package-lock.json" }}

      - run: "if [[ ! -e node_modules ]]; then npm ci; fi"
      - run: "if [[ ! -e client/node_modules ]]; then npm run install:client; fi"
      - run: "if [[ ! -e server/node_modules ]]; then npm run install:server; fi"

      - save_cache:
          key: v2-deps-app-{{ checksum "package-lock.json" }}
          paths:
            - node_modules
      - save_cache:
          key: v2-deps-client-{{ checksum "client/package-lock.json" }}
          paths:
            - client/node_modules
      - save_cache:
          key: v2-deps-server-{{ checksum "server/package-lock.json" }}
          paths:
            - server/node_modules
      - save_cache:
          key: v2-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/repo

  build:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/repo
    steps:
      - restore_cache:
          key: v2-repo-{{ .Environment.CIRCLE_SHA1 }}
      # check latest hash to avoid re-building frontend
      - run: git log --pretty=format'%H' -n 1 -- client > client_checksum
      - restore_cache:
          key: v2-built-client-{{ checksum "client_checksum" }}
      # builds only if the dis dir is not restored
      - run: "if [[ ! -e public/main.bundle.js ]]; then npm run build:prod; fi"
      - save_cache:
          key: v2-built-client-{{ checksum "client_checksum" }}
          paths:
            - public

  commit:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/repo
    steps:
      - restore_cache:
          key: v2-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: npm run commit


  lint:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/repo
    steps:
      - restore_cache:
          key: v2-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: npm run lint

workflows:
  version: 2
  install-build-lint:
    jobs:
      - install
      - build:
          requires:
            - install
      - commit:
          requires:
            - install
      - lint:
          requires:
            - install